services:
  app:
    build: .
    container_name: engkids
    ports:
      - "3000:3000"
    depends_on:
      - engkids_db
      - elasticsearch
#      - logstash
    environment:
#      - LOGSTASH_HOST=logstash
#      - LOGSTASH_PORT=5000
      - PORT=3000
      - DB_HOST=engkids_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=qwerty
      - DB_NAME=engkids_db
      - ELASTICSEARCH_URL=http://elasticsearch:9200
#      - LOGSTASH_HOST=logstash
#      - LOGSTASH_PORT=5000
    networks:
      - app-network
    restart: always

  engkids_db:
    image: postgres:16
    container_name: engkids_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: engkids_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch:
    platform: linux/amd64
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - app-network
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    platform: linux/amd64
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
      - SERVER_HOST=0.0.0.0
      - SERVER_NAME=kibana
      - NODE_OPTIONS=--max-old-space-size=1024
      - STATUS_ALLOWANONYMOUS=true
      - TELEMETRY_ENABLED=false
      - INTERACTIVESETUP_ENABLED=false
    depends_on:
      - elasticsearch
    networks:
      - app-network
    mem_limit: 512m

  setup-kibana:
    image: curlimages/curl:latest
    volumes:
      - ./scripts:/scripts
    command: [ "/bin/sh", "/scripts/setup-kibana.sh" ]
    depends_on:
      - kibana
    networks:
      - app-network

#  logstash:
#    platform: linux/amd64
#    image: docker.elastic.co/logstash/logstash:8.13.0
#    container_name: logstash
#    environment:
#      - LS_JAVA_OPTS=-Xms256m -Xmx256m
#    volumes:
#      - ./logstash/pipeline:/usr/share/logstash/pipeline
#      - ./logstash/config:/usr/share/logstash/config
#    depends_on:
#      - elasticsearch
#    networks:
#      - app-network
#    ports:
#      - "5000:5000"
#    mem_limit: 256m

  filebeat:
    platform: linux/amd64
    image: docker.elastic.co/beats/filebeat:8.13.0
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
#      - /var/log/engkids:/usr/share/filebeat/logs:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - elasticsearch
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  esdata: