services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: engkids
    ports:
      - "5432:5432"
  engkids:
    build: .
    ports:
      - "5050:5050"
    env_file:
      - .env
    depends_on:
      - db