filebeat.inputs:
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message
    include_lines: [ '.*engkids.*' ]
#    exclude_files: [ '.*(elasticsearch|postgres).*' ]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  setup.ilm.enabled: false

setup.kibana:
  host: "http://kibana:5601"
  setup.dashboards.enabled: true

logging.level: warning
