basePath: /
definitions:
  fiber.Map:
    additionalProperties: true
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
    type: object
host: localhost:5050
info:
  contact: {}
  description: This is an API for the EngKids project
  title: EngKids API
  version: "1.0"
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: Login a user with email and password to get a JWT token
      parameters:
      - description: User Login
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Login a user
      tags:
      - auth
  /api/register:
    post:
      consumes:
      - application/json
      description: Register a new user by providing email and password
      parameters:
      - description: User Register
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Register a new user
      tags:
      - auth
swagger: "2.0"
